import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // Global styles should appear last for proper CSS precedence
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import FloatingCart from "./components/cart/FloatingCart";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata: Metadata = {
  title: "E-commerce Website",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Toaster position="bottom-right" />
          {children}
          <FloatingCart />
        </body>
      </html>
    </ClerkProvider>
  );
}
